config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'

  get 'static_pages/home'

  get 'static_pages/help'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#  root   'users#index'
  get    'sessions/new'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/ctrl',    to: 'crs#ctrl'
  resources :users
  #resources :crs,		only:[:new, :create, :edit, :destroy, :show]
  resources :crs do
    collection do
      get :ctrl
      post :ctrl
    end  
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cr.rb
class Cr < ApplicationRecord
  belongs_to :user

  default_scope -> {order(created_at: :desc)}
  validates :Accused, presence: true

  def self.search(search)
    if search
      Cr.where(['id LIKE ?', "%#{search}%"])
    else
      Cr.all
    end
  end

end

app/models/division.rb
class Division < ApplicationRecord
end

app/models/rselect.rb
class Rselect < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :crs, foreign_key: 'user_id'

    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
	  validates :Uid, presence: true, uniqueness: true, length:{is: 8}

  def feed
    Cr.where("user_id = ?", id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    include SessionsHelper


private
  # ログイン済みユーザーかどうか確認
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

end

app/controllers/crs_controller.rb
class CrsController < ApplicationController
  before_action :logged_in_user
  def new
    @cr=Cr.new
    @rselect = Rselect.all
  end

  def create
    @crs = current_user.crs.build(cr_params) if logged_in?
    if @crs.save
      flash[:success] = "record submit"
      redirect_to root_url
    else
      @feed_items = []
      render 'users/show'
    end
  end

  def ctrl
    @cr = Cr.search(params[:search])
  end

  
  def edit
    @cr=Cr.find(params[:id])
  end

  def update
   @cr=Cr.find(params[:id])
   if @cr.update_attributes(officer_params)
     flash.notice = "正常に登録されました"
      redirect_to  ctrl_path
    else
      flash.notice ="probrem occured"
   end
  end

  def show
    @user=User.find_by(params[:Uid])  
    @cr = Cr.find_by(params[:user_id])
  end
    
  def destroy
  end

  private
    def cr_params
      params.require(:cr).permit(:status, :Name, :division, :ext, :Accused,:r_select_id,
                                 :cr_year, :cr_type, :cr_term, :cr_no, :order_r,
                                 :order_ka, :order_fu, :order_jd, :cnt_jd)
    end
    def officer_params
      params.require(:cr).permit(:officer, :Name, :status,:amount_ka,:amount_fu)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(Uid: params[:session][:Uid])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid userID/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	#@user = User.all
    if logged_in?
      @cr = current_user.crs.build
      @feed_items= current_user.feed.paginate(page: params[:page])
    end
  end


  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:home, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]


  def index
    @user = User.all
    if logged_in?
      @cr = current_user.crs.build
      @feed_items= current_user.feed.paginate(page: params[:page])
    end
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "正常に登録されました。"
      redirect_to @user
    else
      render 'new'
    end
  end 
  
  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
    @crs = @user.crs.paginate(page: params[:page])
    #debugger
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end 
  end 

  private
    def user_params
      params.require(:user).permit(:Name, :Uid, :division_id, :ext, :password, :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # ページごとの完全なタイトルを返します。
  def full_title(page_title = '')
    base_title = "Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/crs_helper.rb
module CrsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:Uid] = user.Uid
    #session[:Uid] = user.Uid

  end

  def log_out
    session.delete(:Uid)
    @current_user = nil
  end
  
  #渡されたユーザがログイン済みならtrue
  def current_user?(user)
    user == current_user
  end

  def current_user
    @current_user ||=User.find_by(Uid:session[:Uid])
  end

  def logged_in?
    !current_user.nil?
  end

    # 記憶したURL (もしくはデフォルト値) にリダイレクト
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # アクセスしようとしたURLを覚えておく
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/crs/_cr.html.erb
<li id="cr-<%= cr.id%>">
  <% if cr.status == 1 %>
    <%= button_to '申請中','cr_path', {method: :get, class:"btn btn-danger", id:"btn"}%>
  <% elsif cr.status == 2 %>
    <%= button_to '処理中','#', {method: :get, class:"btn btn-warning", id:"btn"}%>
      <% elsif cr.status == 3 %>
    <%= button_to '貸出中','#', {method: :get, class:"btn btn-success", id:"btn"}%>
  <% elsif cr.status == 4 %>
    <%= button_to '返還済','#', {method: :get, class:"btn btn-primary", id:"btn"}%>
  <% end %>         

  <span class="user"><%= link_to cr.user.Name, cr.user%></span>
  <span class="Accused"><%= cr.Accused %></span>
  <span class="timestamp">
  	Posted <%= time_ago_in_words(cr.created_at) %> ago.
  </span>
</li>

app/views/crs/ctrl.html.erb
<% provide(:title,'Ctrl_Centre') %>
<%
=begin
検索ボックス周り
=end
%>
<%= form_tag ctrl_crs_path, :method => 'get' do %>
<p>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag '検索', :id => nil %>
</p>
<%end%>
<div class="row">
        <div class="col-md-12">
      <table class="table">
        <thead> 
          <th>Status</th>
          <th>division</th> 
          <th>Name</th> 
          <th>ext</th> 

          <th>Doc_ID</th> 
          <th>Accused</th>  
          <th>担当者</th>  
        </thead>
        <% @cr.each do |c| %>

        <tbody>
          <% if c.status == 1 %>
          <td><%= button_to '受付待',edit_cr_path(c), {method: :get, class:"btn btn-danger"}%></td>
          <% elsif c.status == 2 %>
          <td><%= button_to '処理中',edit_cr_path(c), {method: :get, class:"btn btn-warning"}%></td>
          <% elsif c.status == 3 %>
          <td><%= button_to '貸出ok','#', {method: :get, class:"btn btn-success"}%></td>
          <% elsif c.status == 4 %>
          <td><%= button_to '仮出中','#', {method: :get, class:"btn btn-primary"}%></td>
          <% elsif c.status == 5 %>
          <td><%= button_to '返還済','#', {method: :get, class:"btn btn-Secondary"}%></td>

          <% end %>         

          <td><%= c.division %></td>
          <td><%= c.Name %></td>
          <td><%= c.ext %></td>
          <td><%= c.cr_type %></td>
          <td><%= c.Accused %></td>
          <td><%= c.officer %></td>
          <td><%= link_to "返す",'#' %></td>

        </tbody>
        <% end %>

      </table>
        </div>
</div>

app/views/crs/edit.html.erb
<% provide(:title,'Ctrl_edit') %>
<%= form_for(@cr) do |f|%>
  <div class="col-md-12">
    <% f.hidden_field :id%>
    <%= f.text_field :status, value: @cr.status + 1 %>
    <% if @cr.status==1 %>
      <%=f.label :officer, 'Officer in charge'%>
      <%=f.text_field :officer, value: @current_user.Name %>
    <% elsif @cr.status==2 %>
      <%=f.label :amount_ka, 'KA'%>
      <%=f.text_field :amount_ka %>
      <%=f.label :amount_fu, 'FU'%>
      <%=f.text_field :amount_fu %>
    <% else %>
    <% end %>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>  
  <div class="col-md-12">
    <div class="row">
        <%= @cr.division %>
        <%= @cr.Name %>
        <%= @cr.ext %>
        <%= @cr.cr_type %>
        <%= @cr.Accused %>
    </div>
  </div>

app/views/crs/new.html.erb
<% provide(:title, "Entry") %>
<%= form_for(@cr) do |f| %>

  <h1>請求フォーム</h1>
  <%= f.hidden_field :status, value: '1' %>

<%#申請者情報%>
<div class="row">
<div class="col-md-6 col-md-offset-3">

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>division</th>
      <th>ext</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= f.text_field :Name, class: 'form-control', value: @current_user.Name %></td>
      <td>
      <%= f.text_field :division, class: 'form-control', value: @current_user.division_id %></td>
      <td><%= f.text_field :ext, class: 'form-control', value: @current_user.ext %></td>
    </tr>
  </tbody>
</table>

<%#顧客%>
  <div>
    <%= f.label :Accused, "顧客名" %>
    <%= f.text_field :Accused, class: 'form-control' %>
  </div>

<%#番号%>
  <div>
    <%= f.label :r_select_id, "番号区分" %>
  　<%= f.collection_select :r_select_id, @rselect, :rselval, :rselname %>
  </div>

  <div>
    <label>保管・保存番号</label>
    <table>
      <tr>
        <td><%= f.text_field :cr_year, class: 'form-control', placeholder: "年" %></td>
        <td><%= f.text_field :cr_type, class: 'form-control', placeholder: "処理区分" %>
        </td>
        <td><%= f.text_field :cr_no, class: 'form-control', placeholder: "番号" %>
        </td>
      </tr>
    </table>
  </div>
<!--order_rについては、隠しフィールドで保管保存の別を把握
>>r_select_idで把握しているので不要では？
-->

<%#依頼内容%>
  <div class="form-check">
    <lavel class='form-check-label'>
      <label><%= f.check_box :order_ka, {}, true, false %>確定資料</label>
      <label><%= f.check_box :order_fu, {}, true, false %>不提出資料</label>
      <label><%= f.check_box :order_fu, {}, true, false %>test資料</label>
    </lavel>
  </div>

<%#謄本の要否%>
  <div>
    <label><%= f.check_box :order_jd, {}, true, false %>資料要旨の要否</label>
  </div>
  <div>  
    <%= f.label :cnt_jd, "必要部数"%>
    <%= f.text_field :cnt_jd, class: 'form-control' %>
  </div>

  <div>
    <%=  f.submit "Submit", :disable_with => 'Submiting...' %>
  </div>
</div>
</div>


<% end %>

app/views/crs/show.html.erb
<%= form_for(@cr) do |f| %>
  <%= render 'shared/error_messages', object: @user %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

   <div class="field">
    title: <%= @cr.id %>
  </div>
  <div class="field">
    Accused: <%= @cr.Accused %>
  </div>
  <div class="field">
    <%= link_to "Back", root_path, class: "btn btn-lg btn-primary" %>
  </div>
  </div>
</div>
<% end %>

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "sample app", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Help", '#' %></li>

            <% if logged_in? %>
              <li><%= link_to "Users", '#' %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: "delete" %>
                  </li>
                </ul>
              </li>

            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>  
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type,message|%>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_crs_form.html.erb
<%= form_for(@cr) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
    <%#= f.text_area :Accused, placeholder: "Compose new Accused..." %>
  </div>
  <%#= f.submit "Post", class: "btn btn-primary" %>
<%= link_to "Order Cr", new_cr_path, class: "btn btn-lg btn-primary" %>

<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="crs">
    <%= render @feed_items %>
  </ol>
    <%= will_paginate @feed_items %>
  <% end %>

app/views/shared/_user_info.html.erb
<h1><%= current_user.Name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.crs.count, "crs") %></span>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
	<% if logged_in? %>
	  <div class="row">
	    <aside class="col-md-4">
	      <section class="user_info">
	        <%= render 'shared/user_info' %>
	      </section>
	      <section class="micropost_form">
	        <%= render 'shared/crs_form' %>
	      </section>
	    </aside>
	    <div class="col-md-8">
	      <h3>資料一覧</h3>
	      <%= render 'shared/feed' %>
	    </div>
	  </div>
	<% else %>
	  <!--ログインしていない場合の擬似トップ画面 -->
	  <div class="center jumbotron">
	    <h1>Welcome to the Sample App</h1>
	    <h2>
	      This is the home page for the
	      <a href="http://railstutorial.jp/">Ruby on Rails Tutorial</a>
	      sample application.
	    </h2>
	    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
	  </div>
	<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

    <%= f.label :Name, "User Name"%>
    <%= f.text_field :Name, class: 'form-control' %>

    <%= f.label :Uid %>
    <%= f.text_field :Uid, class: 'form-control' %>

    <%= f.label :division_id,"所属" %>
    <%= f.text_field :division_id, class: 'form-control' %>
    <%= f.label :ext, "内線番号" %>
    <%= f.text_field :ext, class: 'form-control' %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation,"Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form'%>
  </div>
</div>

app/views/users/index.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/crs_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>資料一覧</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <!--ログインしていない場合の擬似トップ画面 -->
  <div class="center jumbotron">
    <h1>Welcome to the Sample App</h1>
    <h2>
      This is the home page for the
      <a href="http://railstutorial.jp/">Ruby on Rails Tutorial</a>
      sample application.
    </h2>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title,@user.Name) %>

<div class="row">
  <aside class ="col-md-4">
    <section class="user_info">
        <%= render 'shared/user_info' %>
    </section>
  </aside>
  <div class="col-md-8">
  	<% if @user.crs.any? %>
  		<h3>Case Record (<%= @user.crs.count %>)</h3>
  		<ol class="crs">
  			<%= render @crs %>
		</ol>
		<%= will_paginate @crs %>
	<% end %>
  </div>
</div>      